export const ADD_INCOME_REQUEST = "ADD_INCOME_REQUEST";
export const ADD_INCOME_SUCCESS = "ADD_INCOME_SUCCESS";
export const ADD_INCOME_FAILURE = "ADD_INCOME_FAILURE";

export const ADD_BALANCE_REQUEST = "ADD_BALANCE_REQUEST";
export const ADD_BALANCE_SUCCESS = "ADD_BALANCE_SUCCESS";
export const ADD_BALANCE_FAILURE = "ADD_BALANCE_FAILURE";